### ISSUE TITLE
无法将获取到的所有人文和自然的loads写入文件

### ISSUE THREAD

**Issue by ViolaPioggia** [LgoLgo/cqupt-grabber#8]
**Describe the bug**

无法将获取到的所有人文和自然的loads写入 txt，只能获取最后一行loads，应该是 ioutil.WriteFile 在循环中覆盖了之前的写入

**Additional context**

要是袁神懒得修复可以 assign it to me😘

**Comment by L2ncE** [comment]
这个写的很烂，你有什么想法直接PR把
